### ISSUE TITLE
Found a harmony log on my desktop

### ISSUE THREAD

**Issue by lost-RD** [gnivler/BanditMilitias#1]
Don't know if it will help with diagnosing the issues you're having but here it is. 
[harmony.log.txt](https://github.com/gnivler/BanditMilitias/files/4734061/harmony.log.txt)

Might be from 1.0.0 or from 1.0.1, not sure which. Either way things were weird.

Probably my main issue is that using the hotkey to kill bandit militias wasn't cancelling the battles they were in, leaving other parties bugged.

Another fun behaviour was that occasionally a bandit militia would get bugged out and never move again, then other bandit parties would flock to it but never merge in. They just stood on each other. This happened in a world corner near Charas.

**Comment by gnivler** [comment]
Thanks.  From the extreme departure in functionality change I witnessed, I think the latest update may have had an engine update.  I'm not recommending use of the mod, hidden on Nexus for now.  Next release will have code to unfuck those bad parties.

Just going to close the issue, thanks the same.  Too prototype.   Watch for an update...

**Comment by pardeike** [comment]
Use Env variable to redirect log file

**Comment by gnivler** [comment]
> Use Env variable to redirect log file

thank you for posting sir, for Harmony and all you :)
